[package]
name = "smash-bgm-property"
version = "0.8.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "bgm_property"
path = "src/lib.rs"

[dependencies]
binread = "1.4.0"
binwrite = "0.2.1"
